### ISSUE TITLE
admin doesn't work with ===

### ISSUE THREAD

**Issue by ghost** [rannmann/node-steam-user-trade-tutorial#2]
```
if (offer.partner.getSteamID64() === config.admin || offer.itemsToGive.length === 0)
```

should just check the equality

```
if (offer.partner.getSteamID64() == config.admin || offer.itemsToGive.length === 0)
```

tested it and seems like its working now as intended.

**Comment by rannmann** [comment]
There's actually two issues here.  `config.admin`'s value isn't as it should be and node-steamid returns a string instead of an int.  IIRC in testing using == made it always return true when comparing those two values.  One sec and I'll update the config.
