### ISSUE TITLE
Closes at login attempt

### ISSUE THREAD

**Issue by ryandeming** [rannmann/node-steam-user-trade-tutorial#3]
Hey. I'm assuming this is an issue on my end and not with the code, but I'm really at a loss here. 

I've tried writing my own code, as well as just copying the code directly from here. I've installed all the libraries through npm, as well as the dependencies from the 0.6.8 guide you created (python 2.7, openSSL, windows 7 64bit sdk, and the full version of visual studio). Followed each guide to a T, and on both versions it just ends when trying to login. No errors or anything, just closes out. 

Can't for the life of me figure out what's going wrong. Hoping I might be able to find an answer here.

Thanks!

**Comment by rannmann** [comment]
Without an error there's not much I can do for you.  :(

What nodejs/iojs version are you running and how are you starting the bot?
